name: app_storage
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  sqflite: ^2.3.2
  path: ^1.9.0
  intl: ^0.19.0
  sqflite_common_ffi: ^2.3.3
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/nodispo.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
flutter_icons:
  android: true
  image_path: assets/images/mundobebe.jpeg
